import Foundation

public enum YogaBreath: String, Codable, CaseIterable, Identifiable, Sendable {
    case alternatingNostrils = "Alternating nostrils"
    case bellyRibsChest = "Belly, ribs, chest"
    case breathOfFire = "Breath of fire"
    case chantedRhythm = "Chanted rhythm"
    case deepInAndOut = "Deep in and out"
    case equalCounts = "Equal counts"
    case evenUjjayi = "Even ujjayi"
    case exhaleThenInhale = "Exhale then inhale"
    case exhaleToDrawIn = "Exhale to draw in"
    case exhaleToFold = "Exhale to fold"
    case exhaleToLift = "Exhale to lift"
    case exhaleToLower = "Exhale to lower"
    case exhaleToRound = "Exhale to round"
    case exhaleToTurn = "Exhale to turn"
    case exhaleTwiceInhale = "Exhale twice inhale"
    case forcefulBothWays = "Forceful both ways"
    case heldOnExhale = "Held on exhale"
    case hummingExhale = "Humming exhale"
    case inhaleThroughRolledTongue = "Inhale through rolled tongue"
    case inhaleThroughTeeth = "Inhale through teeth"
    case inhaleToArch = "Inhale to arch"
    case inhaleToFloat = "Inhale to float"
    case inhaleToLengthen = "Inhale to lengthen"
    case inhaleToLift = "Inhale to lift"
    case inhaleToOpen = "Inhale to open"
    case inhaleToRise = "Inhale to rise"
    case longDeepBreath = "Long deep breath"
    case natural = "Natural"
    case onEmptyBreath = "On empty breath"
    case onFullExhale = "On full exhale"
    case onRetention = "On retention"
    case oneBreathPerMovement = "One breath per movement"
    case rapidDiaphragmatic = "Rapid diaphragmatic"
    case ratioCounted = "Ratio-counted"
    case sharpExhales = "Sharp exhales"
    case slowAndEven = "Slow and even"
    case slowAndQuiet = "Slow and quiet"
    case steadyUjjayi = "Steady ujjayi"
    case throatConstricted = "Throat-constricted"
    case withHeldPhases = "With held phases"
    case withTheBreath = "With the breath"

    public var id: String { rawValue }
}

public enum YogaDrishti: String, Codable, CaseIterable, Identifiable, Sendable {
    case ankle = "Ankle"
    case backward = "Backward"
    case betweenFeet = "Between feet"
    case chest = "Chest"
    case downward = "Downward"
    case eyesClosed = "Eyes closed"
    case fixedFlame = "Fixed flame"
    case fixedPoint = "Fixed point"
    case floor = "Floor"
    case floorAhead = "Floor ahead"
    case floorBehind = "Floor behind"
    case forward = "Forward"
    case frontHand = "Front hand"
    case knee = "Knee"
    case nasagra = "Nasagra"
    case navel = "Navel"
    case oppositeHand = "Opposite hand"
    case overShoulder = "Over shoulder"
    case side = "Side"
    case singlePoint = "Single point"
    case toes = "Toes"
    case upward = "Upward"
    case varies = "Varies"
    case wall = "Wall"

    public var id: String { rawValue }
}
